version: '3'
services:
  pingsvc:
    image: kumsub/pingservice
    container_name: ping
    links: 
      - redis
    ports:
      - 8090:8090
    environment:
      - SERVER_PORT = 8090
      - CACHE_TYPE = redis
      - CACHE_HOST = redis
      - CACHE_PORT = 6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  pongsvc:
      image: kumsub/pongservice
      container_name: pong
      ports:
        - 9090:9090
    



  