version: '3'
services:
  pingsvc:
    image: kumsub/ping:v1
    container_name: ping
    ports:
      - 8090:8090
    environment:
      - CACHE_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  pongsvc:
      image: kumsub/pong:v1
      container_name: pong
      ports:
        - 9090:9090
    



  