apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingapi
  namespace: kube-public
spec:
  selector:
    matchLabels:
      name: pingapi
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        name: pingdev
        tier: frontend
    spec:
      containers:
      - name: ping
        image: $WEB_IMAGE_NAME
        ports:
        - name: tcp
          containerPort: 8090
        env:
        - name: SERVER_PORT
          value: "8090"
        - name: CACHE_TYPE
          value: redis
        - name: CACHE_HOST
          value: redis
        - name: CACHE_PORT
          value: "6379"