apiVersion: v1
kind: Service
metadata:
  name: pingservice
  namespace: pingpong
  labels:
    name: pingservice
spec:
  selector:
    name: pingapi 
    tier: frontend
  type: NodePort
  ports:
   - port: 80
     targetPort: 8090
     protocol: TCP
