apiVersion: v1
kind: Service
metadata:
  name: wfe
  namespace: pingpong
  labels:
    name: wfe
spec:
  selector:
    name: web 
  type: LoadBalancer
  ports:
   - port: 6379
     name: redisport
     targetPort: 6379
     protocol: TCP
   - port: 8090
     name: webport
     targetPort: 8090
     protocol: TCP
